"use client";
import { useEffect, useState } from "react";
import Link from "next/link";
import { ProductEmptyState, ProductPageHeader } from "../product-ui";
type Profile={full_name:string;email:string|null;phone:string|null;photoUrl:string|null;country_current:string|null;countries_target:string[];work_right_details:string;linkedin_url:string|null;github_url:string|null;portfolio_url:string|null;base_cv_text:string;onboarding_completed_at:string|null};
export default function ProfileSummary(){const[profile,setProfile]=useState<Profile|null>(null);const[status,setStatus]=useState("Loading profile…");
  useEffect(()=>{void fetch("/api/profile/onboarding").then(async response=>({response,payload:await response.json()})).then(({response,payload})=>{if(!response.ok){setStatus(payload.error);return;}setProfile(payload.data);setStatus("");});},[]);
  if(status)return <section className="workflow-page"><p role="status">{status}</p></section>;
  if(!profile?.onboarding_completed_at)return <section className="workflow-page"><ProductEmptyState title="Complete your profile setup" description="The onboarding wizard collects your basic information, links, photo, and CV evidence."/><Link className="button-primary" href="/dashboard/onboarding">Start setup</Link></section>;
  return <section className="workflow-page"><ProductPageHeader eyebrow="Profile" title={profile.full_name||"Your profile"} description="Your confirmed profile is view-only. Use a focused edit action to revisit the relevant setup step."/><div className="phase-three-detail-grid"><section className="workflow-section">{profile.photoUrl?<img className="profile-onboarding-photo" src={profile.photoUrl} alt={`${profile.full_name} profile`}/>:<p>No profile photo.</p>}<Link className="button-secondary" href="/dashboard/onboarding?edit=photo">Change photo</Link><h2>Contact</h2><p>{profile.email||"No contact email"}</p><p>{profile.phone||"No phone"}</p><Link className="button-secondary" href="/dashboard/onboarding?edit=basic">Edit contact</Link></section><section className="workflow-section"><h2>Location and target markets</h2><p>Current: {profile.country_current||"Not recorded"}</p><p>Targets: {profile.countries_target.join(", ")||"Not recorded"}</p><Link className="button-secondary" href="/dashboard/onboarding?edit=basic">Edit locations</Link><h2>Work authorisation</h2><p>{profile.work_right_details||"Not recorded"}</p><Link className="button-secondary" href="/dashboard/onboarding?edit=work-authorisation">Review work-authorisation details</Link><h2>Professional links</h2><ul>{profile.linkedin_url?<li><a href={profile.linkedin_url} rel="noreferrer" target="_blank">LinkedIn</a></li>:null}{profile.github_url?<li><a href={profile.github_url} rel="noreferrer" target="_blank">GitHub</a></li>:null}{profile.portfolio_url?<li><a href={profile.portfolio_url} rel="noreferrer" target="_blank">Portfolio</a></li>:null}</ul><Link className="button-secondary" href="/dashboard/onboarding?edit=urls">Edit links</Link></section></div><section className="workflow-section"><h2>CV</h2>{profile.base_cv_text?<pre className="profile-cv-text">{profile.base_cv_text}</pre>:<p>No CV evidence saved.</p>}<Link className="button-secondary" href="/dashboard/onboarding?edit=cv">Replace or rebuild CV</Link></section></section>;
}
