// Hand-maintained, honesty-first registry of every job board / ATS / network
// AutoTime claims to support, and exactly what "support" means for each one
// (capture, autofill, native-feed status) plus a public-facing limitation
// string. This is the source of truth behind ats-detector.ts's ATS/API
// detection and the public coverage disclosures shown in the web app (e.g.
// apps/web/lib/coverage-report.ts, apps/web/app/admin/market-data). Keep
// `PLATFORM_NAMES`/`domains`/status fields in sync with reality - this table
// is read as a factual claim, not aspirational status.
export const COVERAGE_STATUSES = [
  "verified", "partial", "manual_only", "unsupported", "unverified", "not_applicable",
] as const;

export type CoverageStatus = (typeof COVERAGE_STATUSES)[number];
export type PlatformCategory = "job_board" | "ats" | "professional_network";
export type PlatformCaptureMode = "api-reference" | "selector-extraction" | "manual-only";

export const PLATFORM_NAMES = [
  "LinkedIn", "Stepstone", "Indeed", "EURES", "EuroTechJobs", "EuroJobs",
  "NextLevelJobs", "Wellfound", "Xing", "WelcomeToTheJungle",
  "NationaleVacaturebank", "InfoJobs", "Monster", "EuroTopTech", "JobTeaser",
  "Greenhouse", "Lever", "Workday", "Ashby", "SmartRecruiters", "iCIMS",
  "BambooHR", "Teamtailor", "Recruitee", "Jobvite", "Personio",
  "Landing.jobs", "Honeypot", "Jobgether", "SwissDevJobs", "NoFluffJobs",
  "CEEhiring", "JustJoin.it", "Jobware",
  "Built In", "Euro Remote", "Remotive", "RemoteOK",
] as const;

export type PlatformName = (typeof PLATFORM_NAMES)[number];

/** One row of the coverage table: what a platform is, and the truthful, per-capability status of AutoTime's support for it. */
export type PlatformCoverage = {
  platform: PlatformName;
  slug: string;
  category: PlatformCategory;
  domains: readonly string[];
  atsKey?: string;
  expectedCaptureMode: PlatformCaptureMode;
  capture: CoverageStatus;
  autofill: CoverageStatus;
  nativeFeed: CoverageStatus;
  lastVerifiedAt: string;
  fixture: string;
  liveCheckUrl: string;
  publicLimitation: string;
};

const VERIFIED_AT = "2026-08-18";
const fixture = (slug: string) => `coverage/${slug}.html`;

export const PLATFORM_COVERAGE: readonly PlatformCoverage[] = [
  { platform:"LinkedIn",slug:"linkedin",category:"professional_network",domains:["linkedin.com"],expectedCaptureMode:"manual-only",capture:"manual_only",autofill:"manual_only",nativeFeed:"not_applicable",lastVerifiedAt:VERIFIED_AT,fixture:fixture("linkedin"),liveCheckUrl:"https://www.linkedin.com/jobs/",publicLimitation:"Manual copy/paste only; AutoTime does not scrape or automate LinkedIn." },
  { platform:"Stepstone",slug:"stepstone",category:"job_board",domains:["stepstone.de","stepstone.com"],expectedCaptureMode:"selector-extraction",capture:"partial",autofill:"not_applicable",nativeFeed:"unsupported",lastVerifiedAt:"2026-09-09",fixture:fixture("stepstone"),liveCheckUrl:"https://www.stepstone.de/jobs",publicLimitation:"Job capture uses visible page data; live-checked 2026-09-09 - \"Ich bin interessiert\" funnels through an account/guest gate to the employer's real external ATS (confirmed: Recruitee), no in-page form of its own." },
  { platform:"Indeed",slug:"indeed",category:"job_board",domains:["indeed.com"],expectedCaptureMode:"selector-extraction",capture:"partial",autofill:"partial",nativeFeed:"unsupported",lastVerifiedAt:VERIFIED_AT,fixture:fixture("indeed"),liveCheckUrl:"https://www.indeed.com/",publicLimitation:"Generic capture and reviewed field filling; page variants can require manual correction." },
  { platform:"EURES",slug:"eures",category:"job_board",domains:["eures.europa.eu","eures.ec.europa.eu"],expectedCaptureMode:"api-reference",capture:"partial",autofill:"not_applicable",nativeFeed:"partial",lastVerifiedAt:VERIFIED_AT,fixture:fixture("eures"),liveCheckUrl:"https://eures.europa.eu/index_en",publicLimitation:"Captures public vacancy references; application handling depends on the originating service." },
  { platform:"EuroTechJobs",slug:"eurotechjobs",category:"job_board",domains:["eurotechjobs.com"],expectedCaptureMode:"selector-extraction",capture:"partial",autofill:"not_applicable",nativeFeed:"unsupported",lastVerifiedAt:"2026-09-09",fixture:fixture("eurotechjobs"),liveCheckUrl:"https://www.eurotechjobs.com/",publicLimitation:"Visible job details only; live-checked 2026-09-09 - \"Apply Now\" opens the employer's own external career site (confirmed: jobs.ea.com), no in-page form." },
  { platform:"EuroJobs",slug:"eurojobs",category:"job_board",domains:["eurojobs.com"],expectedCaptureMode:"selector-extraction",capture:"partial",autofill:"unsupported",nativeFeed:"unsupported",lastVerifiedAt:"2026-09-09",fixture:fixture("eurojobs"),liveCheckUrl:"https://eurojobs.com/",publicLimitation:"Visible job details only; live-checked 2026-09-09 - the apply link requires logging in, and the login page itself is behind a Cloudflare Turnstile challenge (confirmed live, non-headless session) before any credentials can even be entered. A real, specific blocker, not automated around." },
  { platform:"NextLevelJobs",slug:"nextleveljobs",category:"job_board",domains:["nextleveljobs.eu"],expectedCaptureMode:"selector-extraction",capture:"partial",autofill:"not_applicable",nativeFeed:"unsupported",lastVerifiedAt:"2026-09-09",fixture:fixture("nextleveljobs"),liveCheckUrl:"https://nextleveljobs.eu/",publicLimitation:"Visible job details only; live-checked 2026-09-09 - postings link directly to the employer's real external ATS (confirmed: Greenhouse), no in-page form of its own." },
  { platform:"Wellfound",slug:"wellfound",category:"job_board",domains:["wellfound.com","angel.co"],expectedCaptureMode:"selector-extraction",capture:"partial",autofill:"verified",nativeFeed:"unsupported",lastVerifiedAt:"2026-09-08",fixture:fixture("wellfound"),liveCheckUrl:"https://wellfound.com/jobs",publicLimitation:"Reviewed generic capture and field filling (email); the single combined \"Full Name\" field is intentionally left unfilled rather than guessed." },
  { platform:"Xing",slug:"xing",category:"professional_network",domains:["xing.com"],expectedCaptureMode:"selector-extraction",capture:"partial",autofill:"not_applicable",nativeFeed:"unsupported",lastVerifiedAt:VERIFIED_AT,fixture:fixture("xing"),liveCheckUrl:"https://www.xing.com/jobs",publicLimitation:"Public job details only; profile and messaging automation are excluded." },
  { platform:"WelcomeToTheJungle",slug:"welcome-to-the-jungle",category:"job_board",domains:["welcometothejungle.com"],expectedCaptureMode:"selector-extraction",capture:"partial",autofill:"unsupported",nativeFeed:"unsupported",lastVerifiedAt:"2026-09-09",fixture:fixture("welcome-to-the-jungle"),liveCheckUrl:"https://www.welcometothejungle.com/en/jobs",publicLimitation:"Visible job details only; live-checked 2026-09-09 - mixed real behavior, not uniform. Some postings link out to the employer's real external ATS (confirmed: Ashby); others use Welcome to the Jungle's own native apply flow, which hard-requires a Welcome to the Jungle account (email/password or LinkedIn) with no guest option (confirmed live)." },
  { platform:"NationaleVacaturebank",slug:"nationale-vacaturebank",category:"job_board",domains:["nationalevacaturebank.nl"],expectedCaptureMode:"selector-extraction",capture:"partial",autofill:"not_applicable",nativeFeed:"unsupported",lastVerifiedAt:"2026-09-09",fixture:fixture("nationale-vacaturebank"),liveCheckUrl:"https://www.nationalevacaturebank.nl/",publicLimitation:"Visible vacancy capture; Dutch page variants may require manual correction. Live-checked 2026-09-09 - apply button is literally labelled \"solliciteer op website van werkgever\" (apply on employer's website) and confirmed redirects there, no in-page form." },
  { platform:"InfoJobs",slug:"infojobs",category:"job_board",domains:["infojobs.net","infojobs.it"],expectedCaptureMode:"selector-extraction",capture:"partial",autofill:"unsupported",nativeFeed:"unsupported",lastVerifiedAt:"2026-09-08",fixture:fixture("infojobs"),liveCheckUrl:"https://www.infojobs.net/",publicLimitation:"Generic capture only; applying requires a candidate login before any form renders, confirmed live - not something AutoTime can autofill." },
  { platform:"Monster",slug:"monster",category:"job_board",domains:["monster.com","monster.co.uk","monster.de","monster.fr"],expectedCaptureMode:"selector-extraction",capture:"partial",autofill:"unsupported",nativeFeed:"unsupported",lastVerifiedAt:"2026-09-08",fixture:fixture("monster"),liveCheckUrl:"https://www.monster.co.uk/jobs/",publicLimitation:"Generic capture only; regional page variants differ. Real job-posting and search-listing pages return 403 even in a real, non-headless browser session (only the bare homepage returns 200) - re-verified 2026-09-08, not a headless-automation artifact as first assumed; still not confirmed as blocking an actual signed-in human, but the block clearly covers the content the extension would need." },
  { platform:"EuroTopTech",slug:"eurotoptech",category:"job_board",domains:["eurotoptech.com"],expectedCaptureMode:"selector-extraction",capture:"partial",autofill:"unsupported",nativeFeed:"unsupported",lastVerifiedAt:"2026-09-09",fixture:fixture("eurotoptech"),liveCheckUrl:"https://www.eurotoptech.com/jobs",publicLimitation:"Visible job details only. Live-checked 2026-09-09 - this is a paid membership board (confirmed: \"the first 6 roles stay visible; members unlock all 14,517 matching roles, company names, apply links, and full job details\", from €11/month); apply links themselves are not visible without a paid account." },
  { platform:"JobTeaser",slug:"jobteaser",category:"job_board",domains:["jobteaser.com"],expectedCaptureMode:"selector-extraction",capture:"partial",autofill:"not_applicable",nativeFeed:"unsupported",lastVerifiedAt:"2026-09-09",fixture:fixture("jobteaser"),liveCheckUrl:"https://www.jobteaser.com/en/job-offers",publicLimitation:"Public job capture only; institution and sign-in-only flows are excluded. Live-checked 2026-09-09 - a public posting's \"Apply\" button redirects to the employer's real external ATS (confirmed: Personio), no in-page form of its own." },
  { platform:"Landing.jobs",slug:"landing-jobs",category:"job_board",domains:["landing.jobs"],expectedCaptureMode:"selector-extraction",capture:"partial",autofill:"unsupported",nativeFeed:"unsupported",lastVerifiedAt:"2026-09-09",fixture:fixture("landing-jobs"),liveCheckUrl:"https://landing.jobs/at/annea/full-stack-generalist-software-engineer-f-m-x",publicLimitation:"Visible job capture only; live-checked 2026-09-09 - a real posting exposes both \"SIGN UP TO APPLY\" and \"Quick Apply\", but neither reveals a guest application form without creating or signing into a Landing.jobs account." },
  { platform:"Honeypot",slug:"honeypot",category:"job_board",domains:["honeypot.io"],expectedCaptureMode:"selector-extraction",capture:"unsupported",autofill:"unsupported",nativeFeed:"unsupported",lastVerifiedAt:"2026-09-09",fixture:fixture("honeypot"),liveCheckUrl:"https://www.honeypot.io/",publicLimitation:"No current job flow to capture or fill. Live-checked 2026-09-09 - the standalone service was discontinued after its acquisition by XING, and honeypot.io did not serve a reachable jobs site." },
  { platform:"Jobgether",slug:"jobgether",category:"job_board",domains:["jobgether.com"],expectedCaptureMode:"selector-extraction",capture:"partial",autofill:"not_applicable",nativeFeed:"unsupported",lastVerifiedAt:"2026-09-09",fixture:fixture("jobgether"),liveCheckUrl:"https://jobgether.com/offer/697c17f156210e272921ecfc-software-engineer",publicLimitation:"Visible job details only; live-checked 2026-09-09 - the posting's Apply control links directly to the employer's external Personio site, with no Jobgether-hosted application form." },
  { platform:"SwissDevJobs",slug:"swissdevjobs",category:"job_board",domains:["swissdevjobs.ch"],expectedCaptureMode:"selector-extraction",capture:"partial",autofill:"unsupported",nativeFeed:"unsupported",lastVerifiedAt:"2026-09-09",fixture:fixture("swissdevjobs"),liveCheckUrl:"https://swissdevjobs.ch/jobs/10x-Partners-Forward-Deployed-Engineer--Palantir-Foundry-Zurich",publicLimitation:"Visible job capture only; live-checked 2026-09-09 - application handling is mixed. One real posting opened a same-domain form (name, email, CV, motivation and screening fields), while another linked to the employer; native selectors are not promoted until they are verified across at least two native postings." },
  { platform:"NoFluffJobs",slug:"nofluffjobs",category:"job_board",domains:["nofluffjobs.com"],expectedCaptureMode:"selector-extraction",capture:"partial",autofill:"unsupported",nativeFeed:"unsupported",lastVerifiedAt:"2026-09-09",fixture:fixture("nofluffjobs"),liveCheckUrl:"https://nofluffjobs.com/pl/job/software-engineer-java-angular-inteca-remote-3",publicLimitation:"Public listing details are available, but live application-flow verification is blocked: the same real posting that is publicly indexed returns a CloudFront 403 in a real browser session, before its Apply control can be observed." },
  { platform:"CEEhiring",slug:"ceehiring",category:"job_board",domains:["ceehiring.com"],expectedCaptureMode:"selector-extraction",capture:"unsupported",autofill:"unsupported",nativeFeed:"unsupported",lastVerifiedAt:"2026-09-09",fixture:fixture("ceehiring"),liveCheckUrl:"https://ceehiring.com/",publicLimitation:"No current CEE IT job board could be verified. Live-checked 2026-09-09 - ceehiring.com fails DNS resolution; the similarly named ceehiring.corp.ec is an unrelated Ecuadorian corporate portal and is deliberately not treated as this platform." },
  { platform:"JustJoin.it",slug:"justjoin-it",category:"job_board",domains:["justjoin.it"],expectedCaptureMode:"selector-extraction",capture:"partial",autofill:"not_applicable",nativeFeed:"unsupported",lastVerifiedAt:"2026-09-09",fixture:fixture("justjoin-it"),liveCheckUrl:"https://justjoin.it/job-offer/apreel-developer-hd-sas-do-crm-warszawa-data",publicLimitation:"Visible job details only; live-checked 2026-09-09 - Apply redirects from the board to the employer's external Traffit application form, with no JustJoin.it-hosted candidate form." },
  { platform:"Jobware",slug:"jobware",category:"job_board",domains:["jobware.de"],expectedCaptureMode:"selector-extraction",capture:"partial",autofill:"unsupported",nativeFeed:"unsupported",lastVerifiedAt:"2026-09-09",fixture:fixture("jobware"),liveCheckUrl:"https://www.jobware.de/job/r-and-d-software-engineer-m-f-d-063175942",publicLimitation:"Visible job capture only; live-checked 2026-09-09 - the real posting's \"Jetzt bewerben\" control enters a same-domain /apply route that returns Forbidden before an application form or final external destination can be observed." },
  { platform:"Built In",slug:"built-in",category:"job_board",domains:["builtin.com"],expectedCaptureMode:"selector-extraction",capture:"partial",autofill:"unsupported",nativeFeed:"unsupported",lastVerifiedAt:"2026-09-09",fixture:fixture("built-in"),liveCheckUrl:"https://builtin.com/job/java-software-engineer-senior-java-engineer/10658489",publicLimitation:"Visible job details only; live-checked 2026-09-09 - a real European posting offers Easy Apply only through Built In login or account creation, with no guest application form exposed." },
  { platform:"Euro Remote",slug:"euro-remote",category:"job_board",domains:["euroremotejobs.com"],expectedCaptureMode:"selector-extraction",capture:"partial",autofill:"not_applicable",nativeFeed:"unsupported",lastVerifiedAt:"2026-09-09",fixture:fixture("euro-remote"),liveCheckUrl:"https://euroremotejobs.com/job/senior-ml-engineer-europe-based-remote/",publicLimitation:"Visible job details only; live-checked 2026-09-09 - \"Apply for job\" links off-platform to the listing's external source (confirmed: Jobicy), with no Euro Remote-hosted candidate form." },
  { platform:"Remotive",slug:"remotive",category:"job_board",domains:["remotive.com"],expectedCaptureMode:"selector-extraction",capture:"partial",autofill:"not_applicable",nativeFeed:"unsupported",lastVerifiedAt:"2026-09-09",fixture:fixture("remotive"),liveCheckUrl:"https://remotive.com/remote-jobs/software-development/senior-independent-ai-engineer-architect-1919266",publicLimitation:"Visible job details only; live-checked 2026-09-09 - \"Apply for this position\" redirects directly to the employer's external application destination (confirmed: A.Team), with no Remotive-hosted form." },
  { platform:"RemoteOK",slug:"remoteok",category:"job_board",domains:["remoteok.com"],expectedCaptureMode:"selector-extraction",capture:"partial",autofill:"unsupported",nativeFeed:"unsupported",lastVerifiedAt:"2026-09-09",fixture:fixture("remoteok"),liveCheckUrl:"https://remoteok.com/remote-jobs/remote-backend-engineer-rome-air-apps-1131185",publicLimitation:"Visible job details only; live-checked 2026-09-09 - the posting's Apply control targets RemoteOK's /l/1131185 shortlink, which loops back to RemoteOK instead of exposing a candidate form or a verifiable external destination." },
  { platform:"Greenhouse",slug:"greenhouse",category:"ats",domains:["boards.greenhouse.io","job-boards.greenhouse.io"],atsKey:"greenhouse",expectedCaptureMode:"api-reference",capture:"verified",autofill:"verified",nativeFeed:"verified",lastVerifiedAt:"2026-09-02",fixture:fixture("greenhouse"),liveCheckUrl:"https://boards-api.greenhouse.io/v1/boards/stripe/jobs?content=true",publicLimitation:"Native public feed and reviewed field filling; custom employer forms can differ." },
  { platform:"Lever",slug:"lever",category:"ats",domains:["jobs.lever.co"],atsKey:"lever",expectedCaptureMode:"api-reference",capture:"verified",autofill:"verified",nativeFeed:"verified",lastVerifiedAt:"2026-09-02",fixture:fixture("lever"),liveCheckUrl:"https://api.lever.co/v0/postings/palantir?mode=json",publicLimitation:"Native public feed and reviewed field filling; custom questions remain manual." },
  { platform:"Workday",slug:"workday",category:"ats",domains:["myworkdayjobs.com"],atsKey:"workday",expectedCaptureMode:"api-reference",capture:"verified",autofill:"unsupported",nativeFeed:"verified",lastVerifiedAt:"2026-09-09",fixture:fixture("workday"),liveCheckUrl:"https://ubc.wd10.myworkdayjobs.com/wday/cxs/ubc/ubcstaffjobs/jobs",publicLimitation:"Native public feed (undocumented CXS API that powers Workday's own career-site search, a logged exception - see docs/reference/job-aggregation-compliance.md) for job listings; the application form itself is account-gated (plain email/password, no CAPTCHA present) and its autofill outcome is unresolved - see atsFieldMaps.ts. Listings and applying are separate: the feed being public doesn't change autofill's status." },
  { platform:"Ashby",slug:"ashby",category:"ats",domains:["jobs.ashbyhq.com"],atsKey:"ashby",expectedCaptureMode:"api-reference",capture:"verified",autofill:"verified",nativeFeed:"verified",lastVerifiedAt:"2026-09-02",fixture:fixture("ashby"),liveCheckUrl:"https://api.ashbyhq.com/posting-api/job-board/ashby",publicLimitation:"Native public feed and reviewed field filling; custom questions remain manual." },
  { platform:"SmartRecruiters",slug:"smartrecruiters",category:"ats",domains:["jobs.smartrecruiters.com"],atsKey:"smartrecruiters",expectedCaptureMode:"api-reference",capture:"verified",autofill:"unsupported",nativeFeed:"verified",lastVerifiedAt:VERIFIED_AT,fixture:fixture("smartrecruiters"),liveCheckUrl:"https://api.smartrecruiters.com/v1/companies/SmartRecruiters/postings?limit=10&destination=PUBLIC",publicLimitation:"Native public feed metadata; full advert enrichment and custom questions may require review." },
  { platform:"iCIMS",slug:"icims",category:"ats",domains:["icims.com"],atsKey:"icims",expectedCaptureMode:"selector-extraction",capture:"partial",autofill:"unsupported",nativeFeed:"partial",lastVerifiedAt:"2026-09-09",fixture:fixture("icims"),liveCheckUrl:"https://careers.icims.com/",publicLimitation:"Tenant-specific capture only; layouts vary materially. Native feed only exists for \"Jibe-powered\" iCIMS deployments (confirmed live: 2/5 real employer sites tested) - \"classic\" iCIMS portals (3/5 tested) expose no such API at all, so this is deliberately \"partial\", not \"verified\" - see docs/reference/job-aggregation-compliance.md." },
  { platform:"BambooHR",slug:"bamboohr",category:"ats",domains:["bamboohr.com"],atsKey:"bamboohr",expectedCaptureMode:"api-reference",capture:"verified",autofill:"verified",nativeFeed:"verified",lastVerifiedAt:"2026-09-08",fixture:fixture("bamboohr"),liveCheckUrl:"https://avalanche.bamboohr.com/careers/list",publicLimitation:"Native public feed (undocumented-but-stable endpoint, a logged exception - see docs/reference/job-aggregation-compliance.md) and reviewed field filling; custom questions remain manual." },
  { platform:"Teamtailor",slug:"teamtailor",category:"ats",domains:["teamtailor.com"],atsKey:"teamtailor",expectedCaptureMode:"api-reference",capture:"verified",autofill:"verified",nativeFeed:"verified",lastVerifiedAt:"2026-09-08",fixture:fixture("teamtailor"),liveCheckUrl:"https://recruitgo.teamtailor.com/jobs.json",publicLimitation:"Native public feed (undocumented-but-stable endpoint, a logged exception - see docs/reference/job-aggregation-compliance.md) and reviewed field filling; custom questions remain manual." },
  { platform:"Recruitee",slug:"recruitee",category:"ats",domains:["recruitee.com"],atsKey:"recruitee",expectedCaptureMode:"api-reference",capture:"verified",autofill:"verified",nativeFeed:"verified",lastVerifiedAt:"2026-09-08",fixture:fixture("recruitee"),liveCheckUrl:"https://trustedshops.recruitee.com/api/offers/",publicLimitation:"Native public careers feed and reviewed field filling; custom questions remain manual." },
  { platform:"Jobvite",slug:"jobvite",category:"ats",domains:["jobvite.com"],atsKey:"jobvite",expectedCaptureMode:"api-reference",capture:"verified",autofill:"verified",nativeFeed:"verified",lastVerifiedAt:"2026-09-08",fixture:fixture("jobvite"),liveCheckUrl:"https://jobs.jobvite.com/panynj/jobs",publicLimitation:"Native public feed (undocumented-but-stable endpoint discovered via the careers page's own embedded companyEId, a logged exception - see docs/reference/job-aggregation-compliance.md) and reviewed field filling; custom questions remain manual." },
  { platform:"Personio",slug:"personio",category:"ats",domains:["jobs.personio.de","jobs.personio.com"],atsKey:"personio",expectedCaptureMode:"api-reference",capture:"verified",autofill:"verified",nativeFeed:"verified",lastVerifiedAt:"2026-09-08",fixture:fixture("personio"),liveCheckUrl:"https://personio.jobs.personio.de/xml",publicLimitation:"Native public feed and reviewed field filling; employer-specific forms can differ." },
] as const;

/** ATS keys (e.g. "greenhouse", "lever") with a verified native public feed - the platforms ats-detector.ts treats as API-covered. */
export const API_COVERED_ATS = PLATFORM_COVERAGE
  .filter((item) => item.category === "ats" && item.nativeFeed === "verified")
  .map((item) => item.atsKey!) as readonly string[];

/** Identifies which known platform a job URL belongs to by hostname (exact or subdomain match, "www." stripped); null if unrecognised. */
export function getCoveragePlatform(jobUrl: string): PlatformName | null {
  try {
    const hostname = new URL(jobUrl).hostname.toLowerCase().replace(/^www\./, "");
    return PLATFORM_COVERAGE.find((item) =>
      item.domains.some((domain) => hostname === domain || hostname.endsWith(`.${domain}`)),
    )?.platform ?? null;
  } catch { return null; }
}

/** True once a `lastVerifiedAt` date (YYYY-MM-DD) is more than `days` old (default 30) - or if it can't be parsed at all, which is treated as stale. */
export function isCoverageStale(lastVerifiedAt: string, now = new Date(), days = 30) {
  const verified = new Date(`${lastVerifiedAt}T00:00:00.000Z`).getTime();
  return !Number.isFinite(verified) || now.getTime() - verified > days * 86_400_000;
}

/** Aggregate counts (platforms tracked, still-current entries, verified capture/native-feed counts) for the public coverage disclosure page. */
export function getPublicCoverageSummary(now = new Date()) {
  const current = PLATFORM_COVERAGE.filter((item) => !isCoverageStale(item.lastVerifiedAt, now));
  return {
    platforms: PLATFORM_COVERAGE.length,
    currentPlatforms: current.length,
    captureVerified: current.filter((item) => item.capture === "verified").length,
    nativeFeeds: current.filter((item) => item.nativeFeed === "verified").length,
  };
}
