import { type NextRequest, NextResponse } from "next/server";
import { z } from "zod";
import { getRequestUser } from "../../../lib/api-auth";
import { createAdminClient } from "../../../lib/supabase/admin";
import { assertAiRouteRateLimit, draftOutreachWithOpenAI, RateLimitError } from "../../../lib/openai-server";
import { assertCanUseAi, FeatureGateError, trackAiCall } from "../../../lib/feature-gate";
import { isTestAuthUserId } from "../../../lib/test-auth";
const channel = z.enum(["linkedin_note", "linkedin_inmail", "email"]);
const contactType = z.enum(["recruiter","hiring_manager","peer_target_role"]);
const createSchema = z.object({ jobId: z.string().uuid(), jobTitle: z.string().trim().min(1), companyName: z.string().trim().min(1), jobDescription: z.string().trim().min(20), recruiterName: z.string().trim().min(1), recruiterRole: z.string().trim().min(1), recruiterEmail: z.string().email().or(z.literal("")), candidateSummary: z.string().trim().min(20), candidateKeyStrengths: z.array(z.string().trim().min(1)).min(1), channel, contactType: contactType.default("recruiter") });
const updateSchema = z.object({ id: z.string().uuid(), draftSubject: z.string().nullable().optional(), draftBody: z.string().min(1).optional(), status: z.enum(["drafted","sent","replied","no_response"]).optional(), followUpDue: z.string().datetime().nullable().optional() });
export async function GET(request: NextRequest) { try { const { user } = await getRequestUser(request); if (!user) return NextResponse.json({ data: null, error: "Unauthorised" }, { status: 401 }); if (isTestAuthUserId(user.id)) { console.warn("autotime_test_auth_bypass: GET /api/outreach short-circuited by AUTOTIME_TEST_AUTH_ENABLED - returning an empty contact list without reading the database. If this is unexpected, check the AUTOTIME_TEST_AUTH_ENABLED environment variable for this deployment."); return NextResponse.json({ data: { messages: [], jobs: [] }, error: null }); } const client = createAdminClient(); const [outreach, applications] = await Promise.all([client.from("outreach_messages").select("*").eq("user_id", user.id).order("follow_up_due", { ascending: true, nullsFirst: false }), client.from("applications").select("id,title,company,role_title,notes,job_snapshot").eq("user_id", user.id).order("updated_at", { ascending: false })]); const error = outreach.error ?? applications.error; return NextResponse.json({ data: { messages: outreach.data ?? [], jobs: applications.data ?? [] }, error: error?.message ?? null }, { status: error ? 500 : 200 }); } catch (error) { return NextResponse.json({ data: null, error: error instanceof Error ? error.message : "Failed to load contacts" }, { status: 500 }); } }
export async function POST(request: NextRequest) { try { const { user } = await getRequestUser(request); if (!user) return NextResponse.json({ data: null, error: "Unauthorised" }, { status: 401 }); const body = createSchema.parse(await request.json()); await assertAiRouteRateLimit(user.id); await assertCanUseAi(user.id); const result = await draftOutreachWithOpenAI(body); await trackAiCall(user.id, { feature: "outreach-drafting", model: result.model, promptTokens: result.promptTokens, completionTokens: result.completionTokens, costUsd: result.costUsd }); const { data, error } = await createAdminClient().from("outreach_messages").insert({ user_id: user.id, job_id: body.jobId, recruiter_name: body.recruiterName, recruiter_role: body.recruiterRole, recruiter_email: body.recruiterEmail || null, contact_type: body.contactType, channel: body.channel, draft_subject: result.value.subject, draft_body: result.value.body }).select("*").single(); if (error) throw error; return NextResponse.json({ data, error: null }); } catch (error) { const status = error instanceof z.ZodError ? 400 : error instanceof FeatureGateError ? 402 : error instanceof RateLimitError ? 429 : 500; return NextResponse.json({ data: null, error: error instanceof Error ? error.message : "Drafting failed" }, { status }); } }
export async function PATCH(request: NextRequest) { try { const { user } = await getRequestUser(request); if (!user) return NextResponse.json({ data: null, error: "Unauthorised" }, { status: 401 }); const body = updateSchema.parse(await request.json()); const changes = { ...(body.draftSubject !== undefined && { draft_subject: body.draftSubject }), ...(body.draftBody !== undefined && { draft_body: body.draftBody }), ...(body.status !== undefined && { status: body.status, sent_at: body.status === "sent" ? new Date().toISOString() : undefined }), ...(body.followUpDue !== undefined && { follow_up_due: body.followUpDue }) }; const { data, error } = await createAdminClient().from("outreach_messages").update(changes).eq("id", body.id).eq("user_id", user.id).select("*").single(); if (error) throw error; return NextResponse.json({ data, error: null }); } catch (error) { return NextResponse.json({ data: null, error: error instanceof Error ? error.message : "Update failed" }, { status: error instanceof z.ZodError ? 400 : 500 }); } }
