"use client";
import { useEffect, useState, type ChangeEvent } from "react";
import Link from "next/link";
import { useRouter, useSearchParams } from "next/navigation";
import { useDashboardPlan } from "./UserNav";

const completeKey = "autotime-v2-onboarding-complete";
export function markOnboardingComplete(userId: string) { if (typeof window !== "undefined") localStorage.setItem(`${completeKey}:${userId}`, "true"); }
export function hasCompletedOnboarding(userId: string) { return typeof window === "undefined" || localStorage.getItem(`${completeKey}:${userId}`) === "true"; }
type WorkCategory = "eu_eea_swiss_citizen" | "existing_permission" | "sponsorship_required" | "country_specific" | "unsure";
type Values = { fullName:string; email:string; phone:string; countryCurrent:string; countriesTarget:string; workAuthorisationCategory:WorkCategory; workRightDetails:string; linkedinUrl:string; githubUrl:string; portfolioUrl:string; baseCvText:string; photoUrl:string|null };
const empty: Values = { fullName:"",email:"",phone:"",countryCurrent:"",countriesTarget:"",workAuthorisationCategory:"unsure",workRightDetails:"",linkedinUrl:"",githubUrl:"",portfolioUrl:"",baseCvText:"",photoUrl:null };
const labels = ["Basic information", "Work authorisation", "Professional links", "Profile photo", "CV", "Review and confirm"];

function getBuiltCvEvidence(userId: string): string {
  if (typeof window === "undefined") return "";
  try {
    const cv = JSON.parse(localStorage.getItem(`autotime-cv-data:${userId}`) || "null");
    if (!cv || !(cv.contact?.name || cv.summary?.trim() || cv.experience?.length || cv.education?.length || cv.skills?.length)) return "";
    return [
      cv.contact?.name,
      [cv.contact?.email, cv.contact?.phone, cv.contact?.location, cv.contact?.linkedin].filter(Boolean).join(" | "),
      cv.summary,
      ...(cv.experience ?? []).flatMap((item: { title?: string; company?: string; dates?: string; bullets?: string[] }) => [`${item.title ?? ""} — ${item.company ?? ""} (${item.dates ?? ""})`, ...(item.bullets ?? [])]),
      ...(cv.education ?? []).map((item: { degree?: string; institution?: string; dates?: string }) => `${item.degree ?? ""} — ${item.institution ?? ""} (${item.dates ?? ""})`),
      (cv.skills ?? []).join(", "),
    ].filter(Boolean).join("\n");
  } catch { return ""; }
}

export function OnboardingWizard() {
  const router=useRouter(), params=useSearchParams(), {userId}=useDashboardPlan();
  const edit=params.get("edit");
  const requested=edit==="basic"?0:edit==="work-authorisation"?1:edit==="urls"?2:edit==="photo"?3:edit==="cv"?4:null;
  const editing=requested!==null;
  const [validationError,setValidationError]=useState("");
  const [invalidFields,setInvalidFields]=useState<string[]>([]);
  const [step,setStep]=useState(requested??0), [values,setValues]=useState(empty), [status,setStatus]=useState("Loading your setup…");
  const countries=values.countriesTarget.split(",").map(item=>item.trim()).filter(Boolean);
  useEffect(()=>{void fetch("/api/profile/onboarding").then(async response=>({response,payload:await response.json()})).then(({response,payload})=>{if(!response.ok){setStatus(payload.error);return;}const data=payload.data;if(data)setValues({fullName:data.full_name??"",email:data.email??"",phone:data.phone??"",countryCurrent:data.country_current??data.current_country??"",countriesTarget:(data.countries_target??[]).join(", ")||(data.target_countries??""),workAuthorisationCategory:data.work_authorisation_category??"unsure",workRightDetails:data.work_right_details??"",linkedinUrl:data.linkedin_url??"",githubUrl:data.github_url??"",portfolioUrl:data.portfolio_url??"",baseCvText:data.base_cv_text?.trim()||getBuiltCvEvidence(userId),photoUrl:data.photoUrl??null});if(requested===null&&data?.onboarding_completed_at){router.replace("/dashboard/profile");return;}if(requested===null)setStep(Math.min(data?.onboarding_step??0,5));setStatus("");});},[requested,router,userId]);
  const save=async(nextStep:number,complete=false)=>{setStatus("Saving…");const response=await fetch("/api/profile/onboarding",{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({...values,countriesTarget:countries,onboardingStep:nextStep,complete})});const payload=await response.json();if(!response.ok){setStatus(payload.error);return false;}setStatus("");return true;};
  const next=async()=>{setValidationError("");setInvalidFields([]);if(step===0){const invalid=[!values.fullName.trim()?"fullName":"",!values.countryCurrent.trim()?"countryCurrent":"",!countries.length?"countriesTarget":""].filter(Boolean);if(invalid.length){setInvalidFields(invalid);setValidationError("Complete the highlighted fields before continuing.");return;}}if(step===1&&!values.workRightDetails.trim()){setInvalidFields(["workRightDetails"]);setValidationError("Add a factual work-authorisation statement before continuing.");return;}if(step===4&&!values.baseCvText.trim()){setInvalidFields(["baseCvText"]);setValidationError("Add CV evidence, upload a DOCX, or build a CV before continuing.");return;}if(await save(Math.min(step+1,5))){if(editing)router.replace("/dashboard/profile");else setStep(current=>Math.min(current+1,5));}};
  const upload=async(event:ChangeEvent<HTMLInputElement>,kind:"photo"|"cv")=>{const file=event.target.files?.[0];if(!file)return;setStatus(kind==="photo"?"Uploading photo…":"Reading CV…");const body=new FormData();body.set("file",file);const response=await fetch(kind==="photo"?"/api/profile/photo":"/api/profile/import-cv",{method:"POST",body});const payload=await response.json();if(!response.ok){setStatus(payload.error);return;}setValues(current=>kind==="photo"?{...current,photoUrl:payload.data.photoUrl}:{...current,baseCvText:payload.data.text});setStatus(kind==="photo"?"Photo uploaded privately.":"CV extracted. Review it before completing setup.");};
  const reviewWorkAuth=async()=>{setStatus("Checking wording…");const response=await fetch("/api/ai/work-authorisation",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({category:values.workAuthorisationCategory,statement:values.workRightDetails,targetCountries:countries})});const payload=await response.json();if(!response.ok){setStatus(payload.error);return;}setValues(current=>({...current,workRightDetails:payload.data.correctedStatement}));setStatus([payload.data.caution,...payload.data.missingFacts].filter(Boolean).join(" "));};
  const finish=async()=>{if(await save(6,true)){markOnboardingComplete(userId);router.replace("/dashboard/profile");}};
  return <main className="onboarding-wizard-shell"><div className="onboarding-wizard-progress" aria-hidden="true"><span style={{width:`${((step+1)/6)*100}%`}}/></div><p className="eyebrow">Step {step+1} of 6 · {labels[step]}</p><section className="onboarding-step" aria-labelledby="onboarding-title">
    {step===0?<><h1 id="onboarding-title">Basic information</h1><p>Tell us where you are now and which markets you are targeting.</p><label>Full name<input aria-invalid={invalidFields.includes("fullName")} value={values.fullName} onChange={e=>{setValues({...values,fullName:e.target.value});setInvalidFields(fields=>fields.filter(field=>field!=="fullName"))}}/>{invalidFields.includes("fullName")?<span className="onboarding-field-error">Enter your full name.</span>:null}</label><label>Phone<input value={values.phone} onChange={e=>setValues({...values,phone:e.target.value})}/></label><label>Contact email<input type="email" value={values.email} onChange={e=>setValues({...values,email:e.target.value})}/></label><label>Current location<input aria-invalid={invalidFields.includes("countryCurrent")} aria-describedby={invalidFields.includes("countryCurrent")?"current-location-error":undefined} value={values.countryCurrent} onChange={e=>{setValues({...values,countryCurrent:e.target.value});setInvalidFields(fields=>fields.filter(field=>field!=="countryCurrent"))}}/>{invalidFields.includes("countryCurrent")?<span className="onboarding-field-error" id="current-location-error">Enter the country where you currently live.</span>:null}</label><label>Target countries (comma separated)<input aria-invalid={invalidFields.includes("countriesTarget")} value={values.countriesTarget} onChange={e=>{setValues({...values,countriesTarget:e.target.value});setInvalidFields(fields=>fields.filter(field=>field!=="countriesTarget"))}}/>{invalidFields.includes("countriesTarget")?<span className="onboarding-field-error">Add at least one target country.</span>:null}</label></>:null}
    {step===1?<><h1 className="onboarding-work-right-title" id="onboarding-title">What is your current right-to-work position for your target countries?</h1><p>Select the closest factual position. Requirements vary by country; AutoTime does not infer status or provide immigration advice.</p><label>Current position<select value={values.workAuthorisationCategory} onChange={e=>setValues({...values,workAuthorisationCategory:e.target.value as WorkCategory})}><option value="eu_eea_swiss_citizen">I am an EU/EEA/Swiss citizen</option><option value="existing_permission">I already have permission to work in at least one target country</option><option value="sponsorship_required">I will require employer sponsorship</option><option value="country_specific">My position differs by target country</option><option value="unsure">I am unsure and need to verify</option></select></label><label>Explain only facts you have verified<textarea rows={6} value={values.workRightDetails} onChange={e=>setValues({...values,workRightDetails:e.target.value})} placeholder="Example: I hold permission to work in Ireland until [date]. I would require sponsorship for Germany."/></label><button type="button" className="button-secondary" disabled={values.workRightDetails.trim().length<10} onClick={reviewWorkAuth}>AI: check clarity and missing facts</button><p className="onboarding-legal-note">AI can improve wording and identify questions. It cannot determine legal status; verify official sources or seek qualified advice.</p></>:null}
    {step===2?<><h1 id="onboarding-title">Professional links</h1><p>Optional links can enrich your CV later. Nothing is imported automatically.</p>{([['linkedinUrl','LinkedIn URL'],['githubUrl','GitHub URL'],['portfolioUrl','Portfolio URL']] as const).map(([key,label])=><label key={key}>{label}<input type="url" value={values[key]} onChange={e=>setValues({...values,[key]:e.target.value})}/></label>)}</>:null}
    {step===3?<><h1 id="onboarding-title">Profile photo</h1><p>Optional. Photos are stored privately and scoped to your account.</p>{values.photoUrl?<img alt="Profile preview" className="profile-onboarding-photo" src={values.photoUrl}/>:<p>No photo uploaded.</p>}<label>Choose photo<input type="file" accept="image/jpeg,image/png,image/webp" onChange={e=>upload(e,"photo")}/></label></>:null}
    {step===4?<><h1 id="onboarding-title">Add your CV</h1><p className="onboarding-required-note"><strong>Required.</strong> Upload a DOCX, paste CV evidence, or build a new CV before continuing.</p><label>Upload DOCX<input type="file" accept=".docx" onChange={e=>upload(e,"cv")}/></label><label>CV evidence<textarea rows={12} value={values.baseCvText} onChange={e=>setValues({...values,baseCvText:e.target.value})}/></label><Link className="button-secondary" href="/dashboard/cv-tailor?returnTo=%2Fdashboard%2Fonboarding%3Fedit%3Dcv">Build one now</Link></>:null}
    {step===5?<><h1 id="onboarding-title">Review and confirm</h1><dl className="onboarding-review-list"><div><dt>Name</dt><dd>{values.fullName||"Missing"}</dd></div><div><dt>Contact</dt><dd>{values.email||"No email"} · {values.phone||"No phone"}</dd></div><div><dt>Location</dt><dd>{values.countryCurrent||"Missing"}</dd></div><div><dt>Target countries</dt><dd>{countries.join(", ")||"Missing"}</dd></div><div><dt>Work authorisation</dt><dd>{values.workRightDetails||"Missing"}</dd></div><div><dt>Professional links</dt><dd>{[values.linkedinUrl,values.githubUrl,values.portfolioUrl].filter(Boolean).join(" · ")||"None added"}</dd></div><div><dt>Photo</dt><dd>{values.photoUrl?"Added":"Skipped"}</dd></div><div><dt>CV</dt><dd className={values.baseCvText?"review-confirmed":"review-missing"}>{values.baseCvText?`Ready · ${values.baseCvText.length} characters`:"Missing — return to Step 5"}</dd></div></dl></>:null}
    {validationError&&step!==0?<p className="onboarding-validation-alert" role="alert">{validationError}</p>:null}<p role="status">{status}</p><div className="onboarding-actions">{step===5?<button type="button" onClick={finish}>Complete setup</button>:<button type="button" onClick={next}>{editing?"Save changes":step===3?"Continue or skip":"Continue"}</button>}{!editing&&step>0?<button type="button" className="secondary-button" onClick={()=>{setValidationError("");setInvalidFields([]);setStep(current=>current-1)}}>Back</button>:null}</div>
  </section></main>;
}
