"use client";
import { useEffect, useState, type ChangeEvent } from "react";
import { useRouter, useSearchParams } from "next/navigation";
import Link from "next/link";
import { useDashboardPlan } from "./UserNav";

const onboardingCompleteKey="autotime-v2-onboarding-complete";
export function markOnboardingComplete(userId:string){if(typeof window!=="undefined")localStorage.setItem(`${onboardingCompleteKey}:${userId}`,"true");}
export function hasCompletedOnboarding(userId:string){return typeof window==="undefined"||localStorage.getItem(`${onboardingCompleteKey}:${userId}`)==="true";}
type Values={fullName:string;email:string;phone:string;countryCurrent:string;countriesTarget:string;linkedinUrl:string;githubUrl:string;portfolioUrl:string;baseCvText:string;photoUrl:string|null};
const empty:Values={fullName:"",email:"",phone:"",countryCurrent:"",countriesTarget:"",linkedinUrl:"",githubUrl:"",portfolioUrl:"",baseCvText:"",photoUrl:null};
const labels=["Basic information","Professional links","Profile photo","CV","Review and confirm"];
export function OnboardingWizard(){const router=useRouter();const params=useSearchParams();const{userId}=useDashboardPlan();const edit=params.get("edit");const requested=edit==="basic"?0:edit==="urls"?1:edit==="photo"?2:edit==="cv"?3:null;const editing=requested!==null;const[step,setStep]=useState(requested??0);const[values,setValues]=useState(empty);const[status,setStatus]=useState("Loading your setup…");
  useEffect(()=>{void fetch("/api/profile/onboarding").then(async response=>({response,payload:await response.json()})).then(({response,payload})=>{if(!response.ok){setStatus(payload.error);return;}const data=payload.data;if(data)setValues({fullName:data.full_name??"",email:data.email??"",phone:data.phone??"",countryCurrent:data.country_current??data.current_country??"",countriesTarget:(data.countries_target??[]).join(", ")||(data.target_countries??""),linkedinUrl:data.linkedin_url??"",githubUrl:data.github_url??"",portfolioUrl:data.portfolio_url??"",baseCvText:data.base_cv_text??"",photoUrl:data.photoUrl??null});if(requested===null&&data?.onboarding_completed_at){router.replace("/dashboard/profile");return;}if(requested===null)setStep(Math.min(data?.onboarding_step??0,4));setStatus("");});},[requested,router]);
  const countries=values.countriesTarget.split(",").map(item=>item.trim()).filter(Boolean);const save=async(nextStep:number,complete=false)=>{setStatus("Saving…");const response=await fetch("/api/profile/onboarding",{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({fullName:values.fullName,email:values.email,phone:values.phone,countryCurrent:values.countryCurrent,countriesTarget:countries,linkedinUrl:values.linkedinUrl,githubUrl:values.githubUrl,portfolioUrl:values.portfolioUrl,baseCvText:values.baseCvText,onboardingStep:nextStep,complete})});const payload=await response.json();if(!response.ok){setStatus(payload.error);return false;}setStatus("");return true;};
  const next=async()=>{if(await save(Math.min(step+1,4))){if(editing){router.replace("/dashboard/profile");return;}setStep(current=>Math.min(current+1,4));}};const uploadPhoto=async(event:ChangeEvent<HTMLInputElement>)=>{const file=event.target.files?.[0];if(!file)return;setStatus("Uploading photo…");const body=new FormData();body.set("file",file);const response=await fetch("/api/profile/photo",{method:"POST",body});const payload=await response.json();if(response.ok){setValues(current=>({...current,photoUrl:payload.data.photoUrl}));setStatus("Photo uploaded privately.");}else setStatus(payload.error);};const uploadCv=async(event:ChangeEvent<HTMLInputElement>)=>{const file=event.target.files?.[0];if(!file)return;setStatus("Reading CV…");const body=new FormData();body.set("file",file);const response=await fetch("/api/profile/import-cv",{method:"POST",body});const payload=await response.json();if(response.ok){setValues(current=>({...current,baseCvText:payload.data.text}));setStatus("CV extracted. Review it before completing setup.");}else setStatus(payload.error);};
  const finish=async()=>{if(!(values.fullName&&values.countryCurrent&&countries.length&&values.baseCvText)){setStatus("Name, current location, target countries, and CV evidence are required.");return;}if(await save(5,true)){markOnboardingComplete(userId);router.replace("/dashboard/profile");}};
  return <main className="onboarding-wizard-shell"><div className="onboarding-wizard-progress" aria-hidden="true"><span style={{width:`${((step+1)/5)*100}%`}}/></div><p className="eyebrow">Step {step+1} of 5 · {labels[step]}</p><section className="onboarding-step" aria-labelledby="onboarding-title">
    {step===0?<><h1 id="onboarding-title">Basic information</h1><p>Tell us where you are now and which markets you are targeting.</p><label>Full name<input value={values.fullName} onChange={event=>setValues({...values,fullName:event.target.value})}/></label><label>Phone<input value={values.phone} onChange={event=>setValues({...values,phone:event.target.value})}/></label><label>Contact email<input type="email" value={values.email} onChange={event=>setValues({...values,email:event.target.value})}/></label><label>Current location<input value={values.countryCurrent} onChange={event=>setValues({...values,countryCurrent:event.target.value})}/></label><label>Target countries (comma separated)<input value={values.countriesTarget} onChange={event=>setValues({...values,countriesTarget:event.target.value})}/></label></>:null}
    {step===1?<><h1 id="onboarding-title">Professional links</h1><p>Optional links can enrich your CV later. Nothing is imported automatically.</p>{([['linkedinUrl','LinkedIn URL'],['githubUrl','GitHub URL'],['portfolioUrl','Portfolio URL']] as const).map(([key,label])=><label key={key}>{label}<input type="url" value={values[key]} onChange={event=>setValues({...values,[key]:event.target.value})}/></label>)}</>:null}
    {step===2?<><h1 id="onboarding-title">Profile photo</h1><p>Optional. Photos are stored privately and scoped to your account.</p>{values.photoUrl?<img alt="Profile preview" className="profile-onboarding-photo" src={values.photoUrl}/>:<p>No photo uploaded.</p>}<label>Choose photo<input type="file" accept="image/jpeg,image/png,image/webp" onChange={uploadPhoto}/></label></>:null}
    {step===3?<><h1 id="onboarding-title">Add your CV</h1><p>Upload an existing DOCX for extraction, paste CV text, or open the CV builder.</p><label>Upload DOCX<input type="file" accept=".docx" onChange={uploadCv}/></label><label>CV evidence<textarea rows={12} value={values.baseCvText} onChange={event=>setValues({...values,baseCvText:event.target.value})}/></label><Link className="button-secondary" href="/dashboard/cv-tailor">Build one now</Link></>:null}
    {step===4?<><h1 id="onboarding-title">Review and confirm</h1><dl><dt>Name</dt><dd>{values.fullName||"Missing"}</dd><dt>Contact</dt><dd>{values.email||"No email"} · {values.phone||"No phone"}</dd><dt>Location</dt><dd>{values.countryCurrent||"Missing"}</dd><dt>Target countries</dt><dd>{countries.join(", ")||"Missing"}</dd><dt>Professional links</dt><dd>{[values.linkedinUrl,values.githubUrl,values.portfolioUrl].filter(Boolean).join(" · ")||"None added"}</dd><dt>Photo</dt><dd>{values.photoUrl?"Added":"Skipped"}</dd><dt>CV</dt><dd>{values.baseCvText?`${values.baseCvText.length} characters ready`:"Missing"}</dd></dl></>:null}
    <p role="status">{status}</p><div className="onboarding-actions">{step===4?<button type="button" onClick={finish}>Complete setup</button>:<button type="button" onClick={next}>{editing?"Save changes":step===2?"Continue or skip":"Continue"}</button>}{!editing&&step>0?<button type="button" className="secondary-button" onClick={()=>setStep(current=>current-1)}>Back</button>:null}</div>
  </section></main>;
}
