"use client";
import { useEffect, useState } from "react";
import { ProductEmptyState, ProductPageHeader, ProductStatusBadge } from "./product-ui";
type Message = { id: string; job_id: string; recruiter_name: string | null; recruiter_role: string | null; recruiter_email: string | null; contact_type: "recruiter"|"hiring_manager"|"peer_target_role"; channel: "linkedin_note"|"linkedin_inmail"|"email"; draft_subject: string|null; draft_body: string; status: "drafted"|"sent"|"replied"|"no_response"; follow_up_due: string|null };
type Job = { id: string; title: string; company: string|null; role_title: string|null; notes: string|null; job_snapshot: unknown };
const initial = { jobId: "", jobTitle: "", companyName: "", jobDescription: "", recruiterName: "", recruiterRole: "Recruiter", recruiterEmail: "", candidateSummary: "", strengths: "", channel: "email", contactType: "recruiter" };
export default function OutreachWorkspace() { const [messages, setMessages] = useState<Message[]>([]); const [jobs, setJobs] = useState<Job[]>([]); const [form, setForm] = useState(initial); const [status, setStatus] = useState("");
  const load = async () => { const response = await fetch("/api/outreach"); const payload = await response.json(); if (response.ok) { setMessages(payload.data.messages ?? []); setJobs(payload.data.jobs ?? []); } else setStatus(payload.error); }; useEffect(() => { void load(); }, []);
  const update = async (id: string, changes: object) => { const response = await fetch("/api/outreach", { method: "PATCH", headers: { "content-type": "application/json" }, body: JSON.stringify({ id, ...changes }) }); const payload = await response.json(); if (!response.ok) return setStatus(payload.error); setMessages((all) => all.map((item) => item.id === id ? payload.data : item)); };
  return <main className="workflow-page"><ProductPageHeader eyebrow="Human-sent outreach" title="Draft and track recruiter outreach" description="Enter recruiter details manually or from an approved lookup. AutoTime drafts only—it never sends or automates LinkedIn." />
    <section className="workflow-editor"><h2>Draft outreach</h2><div className="workflow-form-grid"><label>Tracked application<select value={form.jobId} onChange={(e) => { const job = jobs.find((item) => item.id === e.target.value); setForm({ ...form, jobId: e.target.value, jobTitle: job?.role_title || job?.title || "", companyName: job?.company || "", jobDescription: job?.notes || JSON.stringify(job?.job_snapshot ?? "") }); }}><option value="">Choose an application</option>{jobs.map((job) => <option key={job.id} value={job.id}>{job.role_title || job.title} — {job.company || "Unknown company"}</option>)}</select></label>{(["jobTitle","companyName","recruiterName","recruiterRole","recruiterEmail","candidateSummary"] as const).map((key) => <label key={key}>{key.replace(/([A-Z])/g," $1")}<input value={form[key]} onChange={(e) => setForm({ ...form, [key]: e.target.value })} /></label>)}
      <label className="full-span">Job description<textarea value={form.jobDescription} onChange={(e) => setForm({ ...form, jobDescription: e.target.value })} /></label><label>Strengths (comma separated)<input value={form.strengths} onChange={(e) => setForm({ ...form, strengths: e.target.value })} /></label><label>Contact type<select value={form.contactType} onChange={(e) => setForm({ ...form, contactType: e.target.value })}><option value="recruiter">Recruiter</option><option value="hiring_manager">Hiring manager</option><option value="peer_target_role">Peer in target role</option></select></label><label>Channel<select value={form.channel} onChange={(e) => setForm({ ...form, channel: e.target.value })}><option value="email">Email</option><option value="linkedin_note">LinkedIn note</option><option value="linkedin_inmail">LinkedIn InMail</option></select></label></div>
      {form.contactType === "peer_target_role" ? <p className="full-span">Peer outreach is informational only: ask for a short conversation about the role or team, not about an application or referral.</p> : null}
      <button className="button-primary" onClick={async () => { setStatus("Drafting…"); const response = await fetch("/api/outreach", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ ...form, candidateKeyStrengths: form.strengths.split(",").map((x) => x.trim()).filter(Boolean) }) }); const payload = await response.json(); if (!response.ok) return setStatus(payload.error); setMessages((all) => [payload.data, ...all]); setStatus("Draft ready. Review before copying."); }}>Draft outreach</button><p role="status">{status}</p></section>
    {messages.length ? <section className="workflow-list">{messages.map((item) => <article className="workflow-list-row" key={item.id}><div><ProductStatusBadge status={item.status === "sent" ? "confirmed" : "inferred"}>{item.status}</ProductStatusBadge><h2>{item.recruiter_name || "Recruiter"}</h2><p>{item.contact_type.replaceAll("_", " ")}</p><input value={item.draft_subject ?? ""} placeholder="No subject for connection notes" onChange={(e) => setMessages((all) => all.map((m) => m.id === item.id ? { ...m, draft_subject: e.target.value } : m))} /><textarea value={item.draft_body} onChange={(e) => setMessages((all) => all.map((m) => m.id === item.id ? { ...m, draft_body: e.target.value } : m))} /></div><div className="workflow-actions"><button className="button-secondary" onClick={() => update(item.id, { draftSubject: item.draft_subject, draftBody: item.draft_body })}>Save edits</button><button className="button-primary" onClick={async () => { await navigator.clipboard.writeText([item.draft_subject, item.draft_body].filter(Boolean).join("\n\n")); const due = new Date(Date.now()+7*86400000).toISOString(); await update(item.id, { status: "sent", followUpDue: due }); setStatus("Copied and marked sent. Follow-up set for 7 days."); }}>Copy and mark sent</button><select value={item.status} onChange={(e) => void update(item.id, { status: e.target.value })}><option value="drafted">Drafted</option><option value="sent">Sent</option><option value="replied">Replied</option><option value="no_response">No response</option></select><input type="datetime-local" value={item.follow_up_due?.slice(0,16) ?? ""} onChange={(e) => void update(item.id, { followUpDue: e.target.value ? new Date(e.target.value).toISOString() : null })} /></div></article>)}</section> : <ProductEmptyState title="No outreach drafts" description="Create a human-reviewed draft for a tracked application." />}
  </main>;
}
