import { readFile } from "node:fs/promises";
import { createClient } from "@supabase/supabase-js";

function parseCsv(text) { const rows=[]; let row=[],field="",quoted=false; for(let i=0;i<text.length;i++){const c=text[i];if(c==='"'){if(quoted&&text[i+1]==='"'){field+='"';i++;}else quoted=!quoted;}else if(c===','&&!quoted){row.push(field);field="";}else if((c==='\n'||c==='\r')&&!quoted){if(c==='\r'&&text[i+1]==='\n')i++;row.push(field);if(row.some(Boolean))rows.push(row);row=[];field="";}else field+=c;}if(field||row.length){row.push(field);rows.push(row);}const [headers,...values]=rows;return values.map((values)=>Object.fromEntries(headers.map((header,index)=>[header.trim(),values[index]?.trim()??""]))); }
const pick=(row,names)=>names.map((name)=>row[name]).find(Boolean)??"";
const splitLabels=(value)=>value.split(/\r?\n|\|/).map((item)=>item.trim()).filter(Boolean);
const uniqueBy=(rows,keyFor)=>[...new Map(rows.map((row)=>[keyFor(row),row])).values()];
async function batches(client, table, rows) { for(let i=0;i<rows.length;i+=500){const {error}=await client.from(table).upsert(rows.slice(i,i+500));if(error)throw new Error(`${table}: ${error.message}`);process.stdout.write(`\r${table}: ${Math.min(i+500,rows.length)}/${rows.length}`);}process.stdout.write("\n"); }
const [skillsPath,occupationsPath,relationsPath]=process.argv.slice(2);if(!skillsPath||!occupationsPath||!relationsPath)throw new Error("Usage: node scripts/import-esco.mjs <skills.csv> <occupations.csv> <occupationSkillRelations.csv>");
const url=process.env.SUPABASE_URL, key=process.env.SUPABASE_SERVICE_ROLE_KEY;if(!url||!key)throw new Error("SUPABASE_URL and SUPABASE_SERVICE_ROLE_KEY are required");const client=createClient(url,key,{auth:{persistSession:false}});
const [skillRows,occupationRows,relationRows]=await Promise.all([skillsPath,occupationsPath,relationsPath].map(async(path)=>parseCsv(await readFile(path,"utf8"))));
const skills=uniqueBy(skillRows.map((row)=>({id:pick(row,["conceptUri","conceptURI","URI"]),preferred_label:pick(row,["preferredLabel","preferred label"]),alt_labels:splitLabels(pick(row,["altLabels","alternative labels"])),skill_type:pick(row,["skillType","skill type"])||null,language:pick(row,["language","languageCode"])||"en"})).filter((row)=>row.id&&row.preferred_label),(row)=>row.id);
const occupations=uniqueBy(occupationRows.map((row)=>({id:pick(row,["conceptUri","conceptURI","URI"]),preferred_label:pick(row,["preferredLabel","preferred label"]),isco_group:pick(row,["iscoGroup","ISCO group"])||null,description:pick(row,["description"])||null,language:pick(row,["language","languageCode"])||"en"})).filter((row)=>row.id&&row.preferred_label),(row)=>row.id);
const relationMap=new Map();for(const row of relationRows.map((row)=>({occupation_id:pick(row,["occupationUri","occupationURI"]),skill_id:pick(row,["skillUri","skillURI"]),relation_type:/essential/i.test(pick(row,["relationType","relation type"]))?"essential":"optional"})).filter((row)=>row.occupation_id&&row.skill_id)){const key=`${row.occupation_id}|${row.skill_id}`;const current=relationMap.get(key);if(!current||row.relation_type==="essential")relationMap.set(key,row);}const relations=[...relationMap.values()];
await batches(client,"esco_skills",skills);await batches(client,"esco_occupations",occupations);await batches(client,"esco_occupation_skills",relations);console.log(`ESCO import complete: ${skills.length} skills, ${occupations.length} occupations, ${relations.length} relations.`);
